In [23]:
import pandas as pd
import numpy as np

# Q1 (pandas version)

In [2]:
print(pd.__version__)

2.0.3


# Download/import housing info

In [3]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv

--2023-09-18 20:18:49--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8000::154, 2606:50c0:8001::154, 2606:50c0:8002::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8000::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1423529 (1.4M) [text/plain]
Saving to: ‘housing.csv’

housing.csv         100%[===================>]   1.36M  --.-KB/s    in 0.1s    

2023-09-18 20:18:49 (14.1 MB/s) - ‘housing.csv’ saved [1423529/1423529]



In [5]:
housing = pd.read_csv("./housing.csv")

# Q2 num. housing columns

Call `pd.DataFrame.info()` to get col info

In [6]:
housing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


# Q3 Which cols have missing vals?

Looking at .info() above shows `total_bedrooms` is the only column with non-null count << nrows

# Q4 Find num unique values for `ocean_proximity` col 

In [17]:
len(housing.ocean_proximity.unique())

5

In [18]:
housing.ocean_proximity.unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [29]:
housing.ocean_proximity.value_counts()

ocean_proximity
<1H OCEAN     9136
INLAND        6551
NEAR OCEAN    2658
NEAR BAY      2290
ISLAND           5
Name: count, dtype: int64

# Q5 Find mean of median house values, for `ocean_proximity` == "NEAR BAY"

In [11]:
housing[housing.ocean_proximity == "NEAR BAY"].median_house_value.mean()

259212.31179039303

# Q6 Missing bedrooms with/without missing values filled

## Value with no modification

In [12]:
housing.total_bedrooms.mean()

537.8705525375618

## Value with `.fillna()` called

In [16]:
housing.total_bedrooms.fillna(537.8705525375618).mean()

537.8705525375617

# Q7

In [26]:
housing_subset = housing[housing.ocean_proximity == "ISLAND"][["housing_median_age", "total_rooms", "total_bedrooms"]]
housing_subset.head()

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [27]:
X = housing_subset.values
type(X)

numpy.ndarray

In [28]:
X.T.shape

(3, 5)

In [25]:
X.shape

(5, 3)

In [33]:
XTX = np.dot(X.T, X)
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [32]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

Create an array y with values [950, 1300, 800, 1000, 1300].
Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
What's the value of the last element of w?

In [38]:
y = [950, 1300, 800, 1000, 1300]
w = np.dot(np.dot(XTX_inv, X.T), y)
w

array([23.12330961, -1.48124183,  5.69922946])